name: tflite_flutter
description: TensorFlow Lite Flutter plugin provides an easy, flexible, and fast Dart API to integrate TFLite models in flutter apps across mobile and desktop platforms.
version: 0.10.0
homepage: https://github.com/hoomanmmd/tflite_flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  quiver: ^3.2.1
  ffi: ^2.0.1

dev_dependencies:

flutter:
  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_plugin
        pluginClass: TfliteFlutterPlugin
      ios:
        pluginClass: TfliteFlutterPlugin
      linux:
        pluginClass: TfliteFlutterPlugin